### ISSUE TITLE
dalek_demo

### ISSUE THREAD

**Issue by kaleb** [vikki/intern_demo#1]
Did you ever author the corresponding dalek version of this?  What are your thoughts of dalek vs intern for functional/integration tests?

**Comment by vikki** [comment]
Yeah I actually wound up putting a lot of it into this repo instead : https://github.com/vikki/if-you-like-it-then-you-should-have-put-a-test-on-it - its all in different branches / folders for comparison - check out the readmes for more detail.

There are lots of things to consider when picking a framework, so it'll depend on what you're after - I did a talk on it but I can write it up if that might be helpful as the slides may be too vague for review without the commentary.

**Comment by kaleb** [comment]
Is there a video of the talk? If not, a write up would be great.
